### PR TITLE
trying to fix incompatibility with matplotlib version 2.0.2 -> 2.1

### PR DESCRIPTION
**Pull request by nikohansen**
thereby solving issue #1638

### CODE REVIEW

**Comment by nikohansen** [comment]
Unfortunately, I don't know how to run a pull-request on the Jenkins nightly build branch.

**Comment by dtusar** [comment]
We currently don't have the nighty build for the master branch but I can prepare one.

**Comment by nikohansen** [comment]
@dtusar, do you understand the problem? To my understanding, the tests must pass _before_ a branch can be pushed to master. I don't exactly see how a nightly build on the master branch would help to solve this problem nor why we would need one.

**Comment by brockho** [comment]
Would it be enough to equip one of the `devel-test` branches with the functionality to call the nightly build by hand in Jenkins? If the answer is yes, I can set this up rather quickly I would guess.

**Comment by dtusar** [comment]
The other option is to have a `test-nightly` branch and every time you make a push to this branch the nightly tests automatically start.

**Comment by nikohansen** [comment]
Isn't the problem that the nightly build, when triggered, pulls from the development branch? If I could push the pull request branch to the nightly build (which is the test that the master branch requires), the problem would be solved.

Setting up a `test-nightly` should work if also the requirements of the master branch are changed, which seems a possible solution.

**Comment by dtusar** [comment]
I created the `test-nightly` branch (from master) and added two new jobs (`Coco-test-nightly` and `Coco-test-nightly-win`) to Jenkins that start when you push something to this branch. I hope this helps.

**Comment by nikohansen** [comment]
FTR, the current master branch fails when tested on the devel-test2 branch.

**Comment by brockho** [comment]
Seems as if the latest renaming of data files causes the problem when running the tests on the master branch: the former `bbob-biobj/2016/RS-4.tgz` is now called `bbob-biobj/2016/RANDOMSEARCH-4_Auger_bbob-biobj.tgz`.

**Pull request merged**
