### PR TITLE
Development

### PR DESCRIPTION
**Pull request by asmaatamna**
transform_vars_*.c that don't update best_parameter now generate a warning if best_parameter is different from zero.

### CODE REVIEW

**Comment by nikohansen** [comment]
To me it looks OK. Can someone else have a look as well?

**Comment by ttusar** [comment]
You might want to consider putting the while loop in a function (since it's been used so often in different places), but other than that, I don't see any problems.

**Comment by nikohansen** [comment]
So should we merge it? The longer we wait, the more likely we (i) will see conflicts and (ii) the introduced bugs will show up in relevant data.

**Comment by ttusar** [comment]
OK from my side.

**Pull request merged**
