### PR TITLE
Added ExampleNonAnytime in Java - RS Algorithm

### PR DESCRIPTION
**Pull request by ElieTrigano**
This example does not support other solver than Random Search yet and a further improvement of the Java implementations and getters could be of use.

### CODE REVIEW

**Comment by olafmersmann** [comment]
We do all development in the `development` branch. Could you rebase your changes on top of that branch instead of `master`? Thanks!

**Comment by olafmersmann** [comment]
Related to issue #1594.

**Comment by brockho** [comment]
Hello. Could you also please check at the same time whether there is nothing missing in the new file? The default [ExampleExperiment.java ](https://github.com/numbbo/coco/blob/master/code-experiments/build/java/ExampleExperiment.java) has around 200 lines, the newly added [ExampleExperimentNonAnytime.java](https://github.com/numbbo/coco/pull/2145/files) only 42. I miss in particular the actual experiment code. Thanks.

**Comment by ElieTrigano** [comment]
Hello everyone, 

Sorry for the mistakes, the request is normally in the correct branch now, and the experiment should be complete. 

Have a nice week!

**Comment by brockho** [comment]
A new [PR](https://github.com/numbbo/coco/pull/2159) has been opened. Thanks.

**Pull request closed without merging**
