### PR TITLE
updating best_parameter in transform_vars_affine.c

### PR DESCRIPTION
**Pull request by asmaatamna**

### CODE REVIEW

**Comment by brockho** [comment]
I suggest to **not merge** this pull request before it does not meet the expectations (ie. providing the correct optimal solution = the same optimal solution than in the old python implementation of COCO, v15.03).

I just tested the code in branch `asma-issue1672` by comparing the `xopt`/`bestparameter` for instance 1 of `f9` in the `bbob` suite in 2-D and get very different numbers.

The new code in this pull request gives `[0.4398782833080097,  1.9129350229865518]` as best parameter but the old python implementation (which allowed to get `xopt` directly) gives me `[-0.03006086,  0.70646751]` as optimum. The function values of a few randomly picked solutions coincide between the two implementations up to the last printed digit such that I expect to have investigated the same function instance in both cases.

**Comment by nikohansen** [comment]
FTR, 
```python
import cma
import cocoex

suite = cocoex.Suite('bbob', '', '')
for i in range(1, 6):
    f9 = cma.ff.BBOB.F9(i)
    f9([1,2])
    print('xopt old:', f9.xopt)
    f9n = suite.get_problem_by_function_dimension_instance(9, 2, i)
    f9n._best_parameter('print')
    with open('._bbob_problem_best_parameter.txt') as f:
        print('xopt new:', f.read())

xopt old: [-0.03006086  0.70646751]
xopt new:  0.4398782833080097  1.9129350229865518 
xopt old: [ 0.70421685 -0.06386419]
xopt new:  1.9084336901453565  0.3722716144957053 
xopt old: [-0.67832142 -0.1996999 ]
xopt new:  -0.8566428390008591  0.1006001910520122 
xopt old: [-0.43917136  0.55419177]
xopt new:  -0.3783427191130627  1.6083835382127760 
xopt old: [-0.40073477 -0.58259046]
xopt new:  -0.3014695378054455  -0.6651809215610790

**Comment by nikohansen** [comment]
FTR, the values also don't agree on `f19`.

**Comment by brockho** [comment]
I checked the code yesterday: the problem seems to be that instead of the correct `M^T(x_opt-b)` for the update of the best parameter from the inner problem's best parameter `x_opt`, the current code computes `M^T(x) - b`. Comments also have to be updated.

**Comment by brockho** [comment]
I am trying to commit a corrected version later today.

**Comment by brockho** [comment]
Could somebody have a look at the latest commit, I did? For me, the code looks correct now and also the first five instances of f9 and f19 are giving the same optimum now between the old code (via the `cma.ff` module) and the current code. I slightly improved (?) the code above to see better whether there is a difference:
```python
import cma
suite = cocoex.Suite('bbob', '', '')
for i in range(1, 6):
    f9 = cma.ff.BBOB.F9(i)
    f9([1,2])
    print('xopt old:', f9.xopt)
    f9n = suite.get_problem_by_function_dimension_instance(9, 2, i)
    f9n._best_parameter('print')
    with open('._bbob_problem_best_parameter.txt') as f:
        xopt_new = np.array((f.read()).split(), dtype=double)
        print('xopt new:', xopt_new)
    if np.abs(f9.xopt[0] - xopt_new[0]) < 1e-8 and np.abs(f9.xopt[1] - xopt_new[1]) < 1e-8:
        print("same")
    else:
        print("different")
```
I just wonder where we should put such a test. We will introduce some new dependency on `cma` which has to be taken care of by the `do.py` I guess?

**Comment by brockho** [comment]
Ah yes, FTR here the output for `f9`:
```
('xopt old:', array([-0.03006086,  0.70646751]))
('xopt new:', array([-0.03006086,  0.70646751]))
same
('xopt old:', array([ 0.70421685, -0.06386419]))
('xopt new:', array([ 0.70421685, -0.06386419]))
same
('xopt old:', array([-0.67832142, -0.1996999 ]))
('xopt new:', array([-0.67832142, -0.1996999 ]))
same
('xopt old:', array([-0.43917136,  0.55419177]))
('xopt new:', array([-0.43917136,  0.55419177]))
same
('xopt old:', array([-0.40073477, -0.58259046]))
('xopt new:', array([-0.40073477, -0.58259046]))
same
```

**Comment by nikohansen** [comment]
Testing all functions in 2-D:
```python
suite = cocoex.Suite('bbob', '', '')
for ifun in range(1, 25):
    for i in range(1, 6):
        fun = eval('cma.ff.BBOB.F%d(i)' % ifun)
        fun([1,2])
        funn = suite.get_problem_by_function_dimension_instance(ifun, 2, i)
        funn._best_parameter('print')
        with open('._bbob_problem_best_parameter.txt') as f:
            xopt = [float(val) for val in f.read().split()]
        if sum((fun.xopt - xopt)**2) > 1e-8:
            print('f%d, i=%d' % (ifun, i))
            print('xopt old:', fun.xopt)
            print('xopt new:', xopt)
```
we see a difference for f9, f19, and f23.
```
f9, i=1
xopt old: [-0.03006086  0.70646751]
xopt new: [0.4398782833080097, 1.9129350229865518]
f9, i=2
xopt old: [ 0.70421685 -0.06386419]
xopt new: [1.9084336901453565, 0.3722716144957053]
f9, i=3
xopt old: [-0.67832142 -0.1996999 ]
xopt new: [-0.8566428390008591, 0.1006001910520122]
f9, i=4
xopt old: [-0.43917136  0.55419177]
xopt new: [-0.3783427191130627, 1.608383538212776]
f9, i=5
xopt old: [-0.40073477 -0.58259046]
xopt new: [-0.3014695378054455, -0.665180921561079]
f19, i=1
xopt old: [-0.1352362   0.69405416]
xopt new: [0.3647638028860506, 1.1940541556608943]
f19, i=2
xopt old: [-0.64194687  0.29648646]
xopt new: [-0.1419468677475828, 0.7964864566705661]
f19, i=3
xopt old: [-0.40838448  0.57725395]
xopt new: [0.0916155246468502, 1.077253947834515]
f19, i=4
xopt old: [ 0.50109967 -0.49889791]
xopt new: [1.0010996688043352, 0.0011020926840989]
f19, i=5
xopt old: [ 0.62828678  0.32443138]
xopt new: [1.1282867822385092, 0.824431378359708]
f23, i=1
xopt old: [ 2.7672  2.1248]
xopt new: [-4.72166803712772, -7.390037956533374]
f23, i=2
xopt old: [ 0.54 -2.  ]
xopt new: [-1.62277922274333, -3.969944013274225]
f23, i=3
xopt old: [ 3.8168  0.1272]
xopt new: [-2.7111318917481357, 0.5724641612332744]
f23, i=4
xopt old: [-2.2904  1.3776]
xopt new: [3.7076852346339955, -9.208131410334484]
f23, i=5
xopt old: [ 1.2568  0.808 ]
xopt new: [2.850248239953795, 0.4784191910801612]
```

**Comment by nikohansen** [comment]
> I just wonder where we should put such a test. We will introduce some new dependency on cma which has to be taken care of by the do.py I guess?

We just copy-paste https://github.com/CMA-ES/pycma/blob/master/cma/bbobbenchmarks.py into this repository.

**Comment by brockho** [comment]
Can it be that the transformation in f23 is not using an orthogonal matrix? Just a thought, not enough time to check because I have to leave right now...

**Comment by asmaatamna** [comment]
With my cma version, I get the following error when I try ```cma.ff.BBOB```
```
AttributeError: 'FitnessFunctions' object has no attribute 'BBOB'
```
When using the old python code however (functions in ```bbobbenchmarks.py```):

```python
import numpy as np
import bbobbenchmarks as bb
import cocoex
import test_suites as ts

def read_best_parameter(problem):
    """This function reads the best parameter of ``problem''
    from a .txt file and returns an array corresponding to
    this best parameter
    """
    problem._best_parameter(what="print")
    with open("._bbob_problem_best_parameter.txt") as f:
        best_parameter = f.read().strip().split()
    return np.array([float(x) for x in best_parameter])

def compare_xopt_old_new(fun_id, dim, instance):
    """Compares old and new optima of a given bbob problem
    with function id ``fun_id'', dimension ``dim'',
    and instance ``instance''. The return statement is
    for testing purposes only
    """
    # Generate old COCO problem and compute its optimum
    fun_old = bb.instantiate(fun_id, instance)
    # Evaluate fun on a random vector to determine the dimension
    fun_old[0](np.zeros(dim))
    # Get old xopt
    xopt_old = fun_old[0]._getxopt()

    # Generate new COCO problem and compute its optimum
    suite = cocoex.Suite("bbob", "", "")
    fun_new = suite.get_problem_by_function_dimension_instance(fun_id, dim, instance)
    # Get new xopt
    xopt_new = read_best_parameter(fun_new)
    
    # Comparing xopt_old and xopt_new
    try:
        assert ts.is_equal(xopt_old, xopt_new)
    except AssertionError:
        print("old xopt =", xopt_old, "new xopt =", xopt_new)
        raise
    
    return xopt_old, xopt_new

f = 23
instances = range(1, 6)
dim = 2

for i in instances:
    print('f%d, i=%d' % (f, i))
    xopt_old, xopt_new = compare_xopt_old_new(f, dim, i)
    print "xopt old:", xopt_old
    print "xopt new:", xopt_new
```
I get the following output:

```
f23, i=1
xopt old: [ 2.7672  2.1248]
xopt new: [ 2.7672  2.1248]
f23, i=2
xopt old: [ 0.54 -2.  ]
xopt new: [ 0.54 -2.  ]
f23, i=3
xopt old: [ 3.8168  0.1272]
xopt new: [ 3.8168  0.1272]
f23, i=4
xopt old: [-2.2904  1.3776]
xopt new: [-2.2904  1.3776]
f23, i=5
xopt old: [ 1.2568  0.808 ]
xopt new: [ 1.2568  0.808 ]
```

**Comment by brockho** [comment]
Can it be that you use an outdated `cma` module? With my `cma`, the above `cma.ff.BBOB` exists.

**Comment by asmaatamna** [comment]
@brockho I was using the release version of ```cma``` which does not include ```cma.ff.BBOB```. The ```github``` version does.

I reran the test in my previous comment using the code ```development``` branch to compare the new and old values of ```xopt``` for ```f23``` and got the same result (i.e. they are equal). I don't understand yet why we obtain different results...

**Comment by brockho** [comment]
@asmaatamna: thanks for checking on your side. We should indeed check/discuss on Tuesday where our differences come from.

**Comment by brockho** [comment]
Not clear yet why @nikohansen does not see the problem on `f_16` and @asmaatamna and @brockho do, but in any case, we should add a check in `transform_vars_affine.c` to not update the best parameter if it is in 0 and the `b` is 0 as well. Then, changing the `NAN` to a `0` in line 71 of `f_weierstrass.c` should solve the problem also on `f_16`.

**Comment by asmaatamna** [comment]
Currently, ```transform_vars_affine.c''' does not check that the transformation matrix is orthogonal. An "orthogonality check" has to be done before computing the inverse transformation in ```transform_vars_affine.c'''. Since this test will be done once, this shouldn't affect the running time much.

**Pull request merged**
