### PR TITLE
Updated setting if the scatter plots will be generated.

### PR DESCRIPTION
**Pull request by dtusar**

### CODE REVIEW

**Comment by dtusar** [comment]
> 
>     If the changed removed a bug, it looks like it left two more bugs unaddressed (next two lines).

I agree, all three should be done the same way.
 
>     the variable genericsettings.isScatter now (still) exists but does not reflect what is actually happening, in the best case it is never touched anywhere.

In my opinion the values in `genericsettings` apply for all runs and if you change them the change stays until you change them back. But the command line flag should affect only the current run.

**Comment by brockho** [comment]
I would also rather argue like @dtusar in his last comment: `genericsettings` should apply to everything, direct changes should stay until changed (back) and genericsettings might be overwritten temporarily for the current run by command line options like `--tab-only`.

Maybe, we can have a `genericsettings.py.in` in the repository that is copied to `genericsetting.py` on installation and the only purpose of which would be to make the default settings easier to retrieve while working interactively with COCO? [maybe there is also a better way of doing so]

**Comment by brockho** [comment]
Thinking again about it, I would like to change my opinion :-) The above actually does not hold for `foreground_algorithm_list`, see also #1507. The reason is that the foreground algorithms are the mandatory input to `cocopp.main`.

**Comment by dtusar** [comment]
Maybe it could hold also for the foreground algorithms and then they wouldn't be mandatory if specified in `genericsettings`.

**Comment by nikohansen** [comment]
> Maybe, we can have a genericsettings.py.in in the repository that is copied to genericsetting.py on installation and the only purpose of which would be to make the default settings easier to retrieve while working interactively with COCO? [maybe there is also a better way of doing so]

You mean like [this](https://github.com/numbbo/coco/blob/development/code-postprocessing/cocopp/rungeneric.py#L188)?

**Comment by brockho** [comment]
Yes, didn't know that we have this already. Would be nice to have this `stored_settings` available as `default_settings` at some point (low priority I would guess because we can also look into the `genericsettings.py` file ourselves).

**Comment by nikohansen** [comment]
Good point, looks like a simple fix of the above hack in `rungeneric.py`.

**Pull request merged**
