### PR TITLE
Took care of a compiler warning.

### PR DESCRIPTION
**Pull request by ttusar**
Found one remaining compiler warning that didn't show on any of the Jenkins machines...

### CODE REVIEW

**Comment by ttusar** [comment]
The appveyor tests failed with the following message:

````
python do.py test-postprocessing
EXPAND	code-postprocessing\setup.py.in to code-postprocessing\setup.py
PYTHON	setup.py install in code-postprocessing
PYTHON	test.py C:\Miniconda\python.exe in code-postprocessing/cocopp
ERROR: return value=1
Post-processing (1)
  downloading http://coco.gforge.inria.fr/data-archive/bbob/2009/BFGS_ros_noiseless.tgz to C:\Users\appveyor\.cocopp\data-archive\bbob\2009\BFGS_ros_noiseless.tgz
Traceback (most recent call last):
  File "C:\Miniconda\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Miniconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Miniconda\lib\site-packages\cocopp-2.2.1.207-py2.7.egg\cocopp\__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "C:\Miniconda\lib\site-packages\cocopp-2.2.1.207-py2.7.egg\cocopp\rungeneric.py", line 291, in main
    args = data_archive.get_extended(args)
  File "C:\Miniconda\lib\site-packages\cocopp-2.2.1.207-py2.7.egg\cocopp\archiving.py", line 850, in get_extended
    res.append(self.get(name, remote=remote))
  File "C:\Miniconda\lib\site-packages\cocopp-2.2.1.207-py2.7.egg\cocopp\archiving.py", line 819, in get
    urlretrieve(url, full_name)
  File "C:\Miniconda\lib\urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "C:\Miniconda\lib\urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "C:\Miniconda\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Miniconda\lib\urllib.py", line 350, in open_http
    h.endheaders(data)
  File "C:\Miniconda\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\Miniconda\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "C:\Miniconda\lib\httplib.py", line 844, in send
    self.connect()
  File "C:\Miniconda\lib\httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "C:\Miniconda\lib\socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 10061] No connection could be made because the target machine actively refused it
*** testing module cocopp ***
python -m  cocopp --no-svg --settings=grayscale BFGS_ros_noiseless
**  subtest 1 finished in  2.12599992752  seconds
Traceback (most recent call last):
  File "test.py", line 428, in <module>
    main(sys.argv[1:])
  File "test.py", line 263, in main
    assert result == 0, 'Test failed: rungeneric on one algorithm with option --conv.'
AssertionError: Test failed: rungeneric on one algorithm with option --conv.
Command exited with code -1
````
Does anyone know what this is about? Can I rerun the Appveryor tests somehow?

**Comment by brockho** [comment]
Looks like a problem with the GForge server when downloading the data for the test.

From my machine everything seems to work currently: I removed some archive files locally in my ```"home"/.cocopp/data-archive/``` and used them in the postprocessing to check that the download works.

Hence, we should see whether a rerun test goes through (which I just initiated).

**Comment by ttusar** [comment]
> Hence, we should see whether a rerun test goes through (which I just initiated).

Thanks! How do you do that?

**Comment by brockho** [comment]
If I click on the `Details` link in the Appveyor entry below (in the list of all tests), I see (after logging in with my Github account) a link on the top right that says something like "re-run the test".

If you do not see it, you should ask @nikohansen for changing your rights, because the Appveyor test is somehow linked to his account (the `Details` link here for example points to `https://ci.appveyor.com/project/nikohansen/coco-j53aywshl8udzvb/build/1.0.1250`.

**Comment by ttusar** [comment]
I don't see that... @nikohansen, can you change my rights? :-)

**Comment by nikohansen** [comment]
I currently don't see where I could change any individual rights. I changed viewing rights to any user rather than administrator. Maybe logging in helps, if you haven't been already. Let me know if the problem persists.

**Comment by ttusar** [comment]
This is what I see when I'm logged in - no option to re-run the test... 

screen shot 2018-06-13 at 22 38 52

**Pull request merged**
