### PR TITLE
Use different name for file object #1496

### PR DESCRIPTION
**Pull request by islandblue**
Changed `f` to `file_obj`, as discussed in #1496

### CODE REVIEW

**Comment by nikohansen** [comment]
Any idea why we see ``Validation failed! File latex_commands_for_html.html should be regenerated!`` in the second and third test that don't run through?

**Comment by brockho** [comment]
I thought I knew what was going on, but now not anymore :-(

Normally, the above message is shown when the `latex_commands_for_html.html` file got outdated. We then have to generate it again with the LaTeX to HTML converter via `python preparehtml.py`. However, when I do this now, there is no change in the file (besides a new date). The error must therefore come from something else. @dtusar: any idea?

**Comment by dtusar** [comment]
I noticed that the generated `html` contains a string which does not exist in the code any more. Perhaps it does not use the latest version of `cocopp`. I have to check this on the slaves.

**Comment by nikohansen** [comment]
Changes merged with ee01661b

**Pull request closed without merging**
