### PR TITLE
closes issue #863

### PR DESCRIPTION
**Pull request by islandblue**
From what I could garner looking at the usage of this function, names always start with alphabetic characters and values consist of non-alphabetic characters. With a couple extra assumptions in this direction, which conform to the present usage, the parser is now immune to white-space.

One unseemly behavior could be that `something: 1, 2, 3 4, 5` is read as `[1, 2, 34, 5]`, but that's bad format anyway. Let me know if we'd like that handled.

### CODE REVIEW

**Comment by ttusar** [comment]
The changes look good to me.

**Comment by nikohansen** [comment]
Looks like an improvement to me and solves the issue. I think @ttusar should have a quick look as well. 

> but that's bad format anyway.

the objective would still be to detect as many user errors as possible with reasonable effort, even if they fall under bad format.

A general remark on the functions `coco_options_read_*(const char *options, const char *name, char *pointer)`: it looks scary to have no information about the allocated space writable under `pointer`.

**Comment by nikohansen** [comment]
Can you comment on what happens to the following input string? 
```
"dimensions: 2, 3, 5, 10 function_indices: 20, 21"
```

**Comment by islandblue** [comment]
> Can you comment on what happens to the following input string?

@nikohansen, could you elaborate?

**Comment by ttusar** [comment]
> I think @ttusar should have a quick look as well.

I did have a look at the code, should I do something else?

**Comment by nikohansen** [comment]
> could you elaborate?

I am trying to understand why in `"dimensions: 2, 3, 5, 10 function_indices: 20, 21"` the space between `10` and `funct...` is not eaten away, or maybe it is but doesn't pose a problem afterwards?

**Comment by islandblue** [comment]
The earlier code interpreted white-space as the end of the value string. The proposed code simply drops all white-space and keeps reading in the rest until it encounters an alphabetic character or the null terminator. Therefore values and following names will never fuse, because values do not have letters in them.

**Comment by islandblue** [comment]
> the objective would still be to detect as many user errors as possible with reasonable effort, even if they fall under bad format.

That is indeed the objective, but to be able to identify this error, additional assumptions are required.

Presently, all this function has to know is...
- names start with an alphabetic character, which can be followed by any sequence of characters
- names are followed by a colon
- values consist of non-alphabetic characters
...however, to be able to identify errors, it needs more information, such as...
- which characters serve as delimiters between elements in an array value
- what other non-delimiter characters are allowed and their expected syntax
...which will expand the definition (and therefore the complexity) of the function significantly.

I'm not saying it will be a complex function in an absolute sense. It will still be a very elementary parsing function. But it will not be what it was before. Please confirm this is what we want, I'll be happy to do it.

**Comment by brockho** [comment]
This issue can be closed after discussing it again today. The current status is enough and we do not want to add complexity to the code to check for other wrong usages.

**Comment by islandblue** [comment]
Looks to me like this pull request was closed without merging to development. I believe this to be in error. @brockho can you confirm?

**Comment by brockho** [comment]
@islandblue: right, the pull request was closed before merging. I apologize for this and will merge it now.

**Pull request merged**
