### PR TITLE
Rw devel mixint ls merge

### PR DESCRIPTION
**Pull request by ttusar**

### CODE REVIEW

**Comment by nikohansen** [comment]
Just FTR (not sure if this applies), there is some risk in merging into the devel-test branches, as their state is not guarantied. A correct sequence to test the current HEAD would be:
```
git push -f coco :devel-test3  # delete remote test branch
git push coco HEAD:devel-test3
```

**Comment by ttusar** [comment]
Thanks for reminding me (again) about the correct procedure.

**Comment by ttusar** [comment]
Oh, just realized my comment above might look a bit snarky - it really wasn't meant to be. The "again" was for me, because I haven't done this in a long time and actually need reminding, although I should have remembered...

**Comment by nikohansen** [comment]
No worries!

**Pull request merged**
