### PR TITLE
Add Rust bindings to main repo.

### LINKED ISSUE #2059: Rust bindings
I wanted to use coco from Rust, so I implemented Rust bindings for it: https://github.com/luleyleo/coco-rs

The readme says
> Contributions to link further languages (including a better example in C++) are more than welcome.

So, I wondered whether I should add a link for the Rust version to the list of languages. Would a PR for that be welcome?

### PR DESCRIPTION
**Pull request by luleyleo**
Closes #2059 

This should integrate the Rust bindings into this repo while still making publishing new versions easy.

As for publishing, Rust crates get published to [crates.io](https://crates.io/).

The packages for the rust bindings are here:
- [coco-rs](https://crates.io/crates/coco-rs)
- [coco-sys](https://crates.io/crates/coco-sys)

In order to publish packages, one needs to be an owner on [crates.io](https://crates.io). Currently only I have the permission to publish. If we are going to keep the code in this repo, it would be good to have someone who is maintaining this project to also be an owner of the crates on [crates.io](https://crates.io).

### CODE REVIEW

**Comment by luleyleo** [comment]
I hope I got the CI somewhat right. But it doesn't seem to list Rust in the `Coco-release-...` tasks yet.

**Comment by nikohansen** [comment]
Cool, be aware that PRs should generally go into the `development` branch. This may also help to get the broken tests fix.

**Comment by nikohansen** [comment]
A test failure probably related to the code changes in the commit looks like
```python
python do.py test-rust
AML	['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/rust/coco-sys/vendor/coco.c
EXPAND	code-experiments/build/rust/coco-sys/vendor/coco.c.in to code-experiments/build/rust/coco-sys/vendor/coco.c
EXPAND	code-experiments/src/coco.h to code-experiments/build/rust/coco-sys/vendor/coco.h
COPY	code-experiments/src/coco_internal.h -> code-experiments/build/rust/coco-sys/vendor/coco_internal.h
WRITE	code-experiments/build/rust/REVISION
WRITE	code-experiments/build/rust/VERSION
Traceback (most recent call last):
  File "do.py", line 1104, in <module>
    main(sys.argv[1:])
  File "do.py", line 1089, in main
    elif cmd == 'test-rust': test_rust()
  File "do.py", line 794, in test_rust
    build_rust()
  File "do.py", line 763, in build_rust
    raise RuntimeError('Can not find cargo path')
RuntimeError: Can not find cargo path
```
see https://ci.appveyor.com/project/nikohansen/coco-28e3ab1txqzfiw9/builds/42722427/job/6me1k71ee2u9aheo

**Comment by nikohansen** [comment]
Is there a reason this code has a different license (MIT) than the rest of the code in the repository (BSD)?

**Comment by luleyleo** [comment]
> Cool, be aware that PRs should generally go into the `development` branch. This may also help to get the broken tests fix.

Oh okay, I will open the PR to the dev branch then.

> A test failure probably related to the code changes in the commit looks like

Oh right, Rust will have to be installed first! Thanks for checking it out! 

> Is there a reason this code has a different license (MIT) than the rest of the code in the repository (BSD)?

Rust packages are usually published under terms of MIT / Apache 2.0, and also I previously published the crates under MIT. So technically dual licensing it under those two would be the proper way.

**Comment by nikohansen** [comment]
> Rust packages are usually published under terms of MIT / Apache 2.0, and also I previously published the crates under MIT. So technically dual licensing it under those two would be the proper way.

Sounds good to me.

To make the tests run through, rebase your commits on the current development branch and then create the PR.

**Pull request merged**
