### PR TITLE
updated constrained testbed and more

### PR DESCRIPTION
**Pull request by paulduf**
Incoming

### CODE REVIEW

**Review by nikohansen — APPROVED** [review]

**Comment by nikohansen** [comment]
I suspect the windows machine is down?

**Comment by nikohansen** [comment]
I started the ...-release-... tests, but I am not sure the tests were deployed on this PR.

**Comment by nikohansen** [comment]
I started the ...-release-... tests, but I am not sure the tests were deployed on this PR.

**Comment by nikohansen** [comment]
I don't understand the invisioned workflow. It seems that the ...release... tests are run on the latest release, so then can only be done _after_ the release, while they should be done before?

**Comment by ttusar** [comment]
Didn’t we usually follow the workflow:
1. Development branch ready for release
2. Pull the development branch to the release branch
3. Run all the tests on the release branch
4. Push the release branch to the master branch

**Comment by nikohansen** [comment]
I see, makes sense, except that release isn't an intuitive description for the precondition to get into the master branch.

@paulduf I infer that you should make this pull request to the release branch instead of master.

**Pull request closed without merging**
