### PR TITLE
sorting of data to make output depend only on random seed

### PR DESCRIPTION
**Pull request by brockho**

### CODE REVIEW

**Comment by brockho** [comment]
@FloopCZ: my latest commit in COCO follows your suggestion at GECCO regarding the "file not closed" warnings under python 3. I hope you did not already start to touch this.

**Comment by FloopCZ** [comment]
Hi @brockho, I have already fixed those warnings in #1457 in [this commit](https://github.com/numbbo/coco/pull/1457/commits/1b8f6a00fff6807cc3de68ef628415d0c2d0e581) about a week ago. Please merge #1457 into your branch.

**Comment by brockho** [comment]
Ah, sorry. I did not check deeply enough your commits. I should become more used to having open pull requests it seems :-)

**Comment by FloopCZ** [comment]
I should have marked the pull request [WIP], so that it was obvious that more changes were coming. However, it was unexpected. I just fixed it one evening and did not want to create a new PR, since it was a related issue.

**Comment by brockho** [comment]
I will close this pull request as it will most likely give a conflict anyway due to the fact that @FloopCZ was quicker than me :-)

**Pull request closed without merging**
